"""
OneDrive File Management Service
MCP Protocol Handlers - Auto-generated from tool_config.yaml
Generated at: 2025-11-11T17:21:47.223768
Source config: modules/onedrive_mcp/tool_config.yaml

DO NOT EDIT THIS FILE DIRECTLY
Modify tool_config.yaml and regenerate using:
python scripts/generate_handlers.py --config modules/onedrive_mcp/tool_config.yaml
"""

import json
from typing import Any, Dict, List, Optional
from mcp.types import Tool, TextContent, Prompt, PromptArgument, PromptMessage

from infra.core.logger import get_logger
from infra.core.tool_registry import ToolRegistry, ToolConfig
from .onedrive_handler import OneDriveHandler
from .schemas import (    ListFilesRequest,    ListFilesResponse,    ReadFileRequest,    ReadFileResponse,    WriteFileRequest,    WriteFileResponse,    DeleteFileRequest,    DeleteFileResponse,)
logger = get_logger(__name__)


class OneDriveHandlers:
    """OneDrive File Management Service MCP Protocol Handlers"""

    def __init__(self):
        """Initialize handlers with tools instance and registry"""
        self.onedrive_handler = OneDriveHandler()
        self.registry = ToolRegistry()
        self._register_tools()
        logger.info("✅ OneDriveHandlers initialized with 5 tools")

    def _register_tools(self):
        """Register all tools in the registry"""
        # list_files: OneDrive 파일 및 폴더 목록을 조회합니다. folder_path를 지정하면 해당 폴더의 파일을 조회하...
        self.registry.register(
            ToolConfig(
                name="list_files",
                description="OneDrive 파일 및 폴더 목록을 조회합니다. folder_path를 지정하면 해당 폴더의 파일을 조회하고, search를 지정하면 검색을 수행합니다.",                request_class=ListFilesRequest,                response_class=ListFilesResponse,                method=self.onedrive_handler.list_files,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "name": "user_id", "required": False, "type": "string"}, {"description": "\ud3f4\ub354 \uacbd\ub85c (\uc608: Documents/MyFolder, \uc0dd\ub7b5 \uc2dc \ub8e8\ud2b8)", "name": "folder_path", "required": False, "type": "string"}, {"description": "\uac80\uc0c9\uc5b4", "name": "search", "required": False, "type": "string"}],            )
        )
        # read_file: OneDrive 파일의 내용을 읽어옵니다. 텍스트 파일은 텍스트로, 바이너리 파일은 Base64 인코딩으로 ...
        self.registry.register(
            ToolConfig(
                name="read_file",
                description="OneDrive 파일의 내용을 읽어옵니다. 텍스트 파일은 텍스트로, 바이너리 파일은 Base64 인코딩으로 반환합니다.",                request_class=ReadFileRequest,                response_class=ReadFileResponse,                method=self.onedrive_handler.read_file,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "name": "user_id", "required": False, "type": "string"}, {"description": "\ud30c\uc77c \uacbd\ub85c \ub610\ub294 \ud30c\uc77c ID (\uc608: Documents/myfile.txt)", "name": "file_path", "required": True, "type": "string"}],            )
        )
        # write_file: OneDrive에 파일을 생성하거나 덮어씁니다. 기본적으로 기존 파일을 덮어쓰며, overwrite=fals...
        self.registry.register(
            ToolConfig(
                name="write_file",
                description="OneDrive에 파일을 생성하거나 덮어씁니다. 기본적으로 기존 파일을 덮어쓰며, overwrite=false로 설정하면 덮어쓰기를 방지합니다.",                request_class=WriteFileRequest,                response_class=WriteFileResponse,                method=self.onedrive_handler.write_file,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "name": "user_id", "required": False, "type": "string"}, {"description": "\ud30c\uc77c \uacbd\ub85c (\uc608: Documents/myfile.txt)", "name": "file_path", "required": True, "type": "string"}, {"description": "\ud30c\uc77c \ub0b4\uc6a9", "name": "content", "required": True, "type": "string"}, {"default": True, "description": "\uae30\uc874 \ud30c\uc77c \ub36e\uc5b4\uc4f0\uae30 \ud5c8\uc6a9 \uc5ec\ubd80", "name": "overwrite", "required": False, "type": "boolean"}],            )
        )
        # delete_file: OneDrive 파일 또는 폴더를 삭제합니다....
        self.registry.register(
            ToolConfig(
                name="delete_file",
                description="OneDrive 파일 또는 폴더를 삭제합니다.",                request_class=DeleteFileRequest,                response_class=DeleteFileResponse,                method=self.onedrive_handler.delete_file,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "name": "user_id", "required": False, "type": "string"}, {"description": "\ud30c\uc77c \ub610\ub294 \ud3f4\ub354 \uacbd\ub85c (\uc608: Documents/myfile.txt)", "name": "file_path", "required": True, "type": "string"}],            )
        )
        # create_folder: OneDrive에 새 폴더를 생성합니다....
        self.registry.register(
            ToolConfig(
                name="create_folder",
                description="OneDrive에 새 폴더를 생성합니다.",                request_class=dict,                response_class=dict,                method=self.onedrive_handler.create_folder,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "name": "user_id", "required": False, "type": "string"}, {"description": "\uc0dd\uc131\ud560 \ud3f4\ub354 \uacbd\ub85c (\uc608: Documents/NewFolder)", "name": "folder_path", "required": True, "type": "string"}],            )
        )

    # ========================================================================
    # MCP Protocol: list_tools
    # ========================================================================

    async def handle_list_tools(self) -> List[Tool]:
        """List available MCP tools"""
        logger.info("🔧 [MCP Handler] list_tools() called")
        return self.registry.list_tools()

    # ========================================================================
    # MCP Protocol: call_tool
    # ========================================================================

    async def handle_call_tool(
        self,
        name: str,
        arguments: Dict[str, Any],
        authenticated_user_id: Optional[str] = None
    ) -> List[TextContent]:
        """Handle MCP tool calls"""
        logger.info(f"🔨 [MCP Handler] call_tool({name}) with args: {arguments}")

        try:            # 인증 기반 user_id 강제 적용 (검색 계열 툴에만 해당)
            auth_tools = ["list_files", "read_file", "write_file", "delete_file", "create_folder"]
            if name in auth_tools:
                from infra.core.auth_helpers import get_authenticated_user_id

                # 도구별 인증 필드 매핑
                auth_fields = {                    "list_files": "user_id",                    "read_file": "user_id",                    "write_file": "user_id",                    "delete_file": "user_id",                    "create_folder": "user_id",                }

                auth_field = auth_fields.get(name, "user_id")
                provided_user = arguments.get(auth_field)

                # 공통 헬퍼 적용
                resolved_user = get_authenticated_user_id(
                    {"user_id": provided_user} if provided_user else {},
                    authenticated_user_id,
                )

                # 보안 검증 로깅
                if authenticated_user_id and provided_user and provided_user != authenticated_user_id:
                    logger.warning(
                        f"⚠️ 보안: 인증된 user_id({authenticated_user_id})와 파라미터 {auth_field}({provided_user})가 다름. 인증된 user_id 사용."
                    )

                if resolved_user:
                    arguments[auth_field] = resolved_user
            # Registry를 통한 도구 실행
            response = await self.registry.call_tool(
                name=name,
                arguments=arguments,
                authenticated_user_id=authenticated_user_id
            )

            # 응답 포맷팅
            if hasattr(response, 'message'):
                return [TextContent(type="text", text=response.message)]
            elif hasattr(response, 'model_dump_json'):
                return [TextContent(type="text", text=response.model_dump_json(indent=2))]
            else:
                return [TextContent(type="text", text=str(response))]

        except ValueError as e:
            error_msg = str(e)
            logger.error(error_msg)
            return [
                TextContent(
                    type="text",
                    text=json.dumps(
                        {"success": False, "message": error_msg}, indent=2
                    ),
                )
            ]

        except Exception as e:
            logger.error(f"❌ Tool 실행 오류: {name}, {str(e)}", exc_info=True)
            error_response = {"success": False, "message": f"오류 발생: {str(e)}"}
            return [
                TextContent(type="text", text=json.dumps(error_response, indent=2))
            ]

    # ========================================================================
    # Helper: Convert to dict (for HTTP responses)
    # ========================================================================

    async def call_tool_as_dict(
        self,
        name: str,
        arguments: Dict[str, Any],
        authenticated_user_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        HTTP API용 헬퍼: call_tool 결과를 dict로 반환

        MCP는 TextContent를 반환하지만,
        HTTP API는 JSON dict를 반환해야 하므로 변환 헬퍼 제공
        """
        try:
            response = await self.registry.call_tool(
                name=name,
                arguments=arguments,
                authenticated_user_id=authenticated_user_id
            )

            if hasattr(response, 'model_dump'):
                return response.model_dump()
            elif hasattr(response, '__dict__'):
                return response.__dict__
            else:
                return {"result": str(response)}

        except Exception as e:
            logger.error(f"❌ Tool 실행 오류: {name}, {str(e)}", exc_info=True)
            raise