"""
Calendar Management Service
MCP Protocol Handlers - Auto-generated from tool_config.yaml
Generated at: 2025-11-11T17:29:52.773464
Source config: modules/calendar_mcp/tool_config.yaml

DO NOT EDIT THIS FILE DIRECTLY
Modify tool_config.yaml and regenerate using:
python scripts/generate_handlers.py --config modules/calendar_mcp/tool_config.yaml
"""

import json
from typing import Any, Dict, List, Optional
from mcp.types import Tool, TextContent, Prompt, PromptArgument, PromptMessage

from infra.core.logger import get_logger
from infra.core.tool_registry import ToolRegistry, ToolConfig
from .calendar_handler import CalendarHandler
from .schemas import (    ListEventsRequest,    ListEventsResponse,    CreateEventRequest,    CreateEventResponse,    UpdateEventRequest,    UpdateEventResponse,    DeleteEventRequest,    DeleteEventResponse,    GetEventRequest,    GetEventResponse,)
logger = get_logger(__name__)


class CalendarHandlers:
    """Calendar Management Service MCP Protocol Handlers"""

    def __init__(self):
        """Initialize handlers with tools instance and registry"""
        self.calendar_handler = CalendarHandler()
        self.registry = ToolRegistry()
        self._register_tools()
        logger.info("✅ CalendarHandlers initialized with 5 tools")

    def _register_tools(self):
        """Register all tools in the registry"""
        # calendar_list_events: 캘린더 이벤트 목록을 조회합니다....
        self.registry.register(
            ToolConfig(
                name="calendar_list_events",
                description="캘린더 이벤트 목록을 조회합니다.",                request_class=ListEventsRequest,                response_class=ListEventsResponse,                method=self.calendar_handler.list_events,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID", "name": "user_id", "required": True, "type": "string"}, {"description": "\uc2dc\uc791 \uc2dc\uac04 (ISO 8601 \ud615\uc2dd, \uc608: 2025-01-15T00:00:00)", "name": "start_datetime", "required": False, "type": "string"}, {"description": "\uc885\ub8cc \uc2dc\uac04 (ISO 8601 \ud615\uc2dd, \uc608: 2025-01-15T23:59:59)", "name": "end_datetime", "required": False, "type": "string"}, {"default": 100, "description": "\ucd5c\ub300 \uacb0\uacfc \uc218", "name": "max_results", "required": False, "type": "integer"}],            )
        )
        # calendar_create_event: 새 캘린더 이벤트를 생성합니다....
        self.registry.register(
            ToolConfig(
                name="calendar_create_event",
                description="새 캘린더 이벤트를 생성합니다.",                request_class=CreateEventRequest,                response_class=CreateEventResponse,                method=self.calendar_handler.create_event,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID", "name": "user_id", "required": True, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 \uc81c\ubaa9", "name": "subject", "required": True, "type": "string"}, {"description": "\uc2dc\uc791 \uc2dc\uac04 (ISO 8601 \ud615\uc2dd)", "name": "start_datetime", "required": True, "type": "string"}, {"description": "\uc885\ub8cc \uc2dc\uac04 (ISO 8601 \ud615\uc2dd)", "name": "end_datetime", "required": True, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 \ub0b4\uc6a9", "name": "body_content", "required": False, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 \uc704\uce58", "name": "location", "required": False, "type": "string"}],            )
        )
        # calendar_update_event: 기존 캘린더 이벤트를 업데이트합니다....
        self.registry.register(
            ToolConfig(
                name="calendar_update_event",
                description="기존 캘린더 이벤트를 업데이트합니다.",                request_class=UpdateEventRequest,                response_class=UpdateEventResponse,                method=self.calendar_handler.update_event,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID", "name": "user_id", "required": True, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 ID", "name": "event_id", "required": True, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 \uc81c\ubaa9", "name": "subject", "required": False, "type": "string"}, {"description": "\uc2dc\uc791 \uc2dc\uac04 (ISO 8601 \ud615\uc2dd)", "name": "start_datetime", "required": False, "type": "string"}, {"description": "\uc885\ub8cc \uc2dc\uac04 (ISO 8601 \ud615\uc2dd)", "name": "end_datetime", "required": False, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 \ub0b4\uc6a9", "name": "body_content", "required": False, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 \uc704\uce58", "name": "location", "required": False, "type": "string"}],            )
        )
        # calendar_delete_event: 캘린더 이벤트를 삭제합니다....
        self.registry.register(
            ToolConfig(
                name="calendar_delete_event",
                description="캘린더 이벤트를 삭제합니다.",                request_class=DeleteEventRequest,                response_class=DeleteEventResponse,                method=self.calendar_handler.delete_event,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID", "name": "user_id", "required": True, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 ID", "name": "event_id", "required": True, "type": "string"}],            )
        )
        # calendar_get_event: 특정 캘린더 이벤트의 상세 정보를 조회합니다....
        self.registry.register(
            ToolConfig(
                name="calendar_get_event",
                description="특정 캘린더 이벤트의 상세 정보를 조회합니다.",                request_class=GetEventRequest,                response_class=GetEventResponse,                method=self.calendar_handler.get_event,                auth_required=True,                auth_field="user_id",                parameters=[{"description": "\uc0ac\uc6a9\uc790 ID", "name": "user_id", "required": True, "type": "string"}, {"description": "\uc774\ubca4\ud2b8 ID", "name": "event_id", "required": True, "type": "string"}],            )
        )

    # ========================================================================
    # MCP Protocol: list_tools
    # ========================================================================

    async def handle_list_tools(self) -> List[Tool]:
        """List available MCP tools"""
        logger.info("🔧 [MCP Handler] list_tools() called")
        return self.registry.list_tools()

    # ========================================================================
    # MCP Protocol: call_tool
    # ========================================================================

    async def handle_call_tool(
        self,
        name: str,
        arguments: Dict[str, Any],
        authenticated_user_id: Optional[str] = None
    ) -> List[TextContent]:
        """Handle MCP tool calls"""
        logger.info(f"🔨 [MCP Handler] call_tool({name}) with args: {arguments}")

        try:            # 인증 기반 user_id 강제 적용 (검색 계열 툴에만 해당)
            auth_tools = ["calendar_list_events", "calendar_create_event", "calendar_update_event", "calendar_delete_event", "calendar_get_event"]
            if name in auth_tools:
                from infra.core.auth_helpers import get_authenticated_user_id

                # 도구별 인증 필드 매핑
                auth_fields = {                    "calendar_list_events": "user_id",                    "calendar_create_event": "user_id",                    "calendar_update_event": "user_id",                    "calendar_delete_event": "user_id",                    "calendar_get_event": "user_id",                }

                auth_field = auth_fields.get(name, "user_id")
                provided_user = arguments.get(auth_field)

                # 공통 헬퍼 적용
                resolved_user = get_authenticated_user_id(
                    {"user_id": provided_user} if provided_user else {},
                    authenticated_user_id,
                )

                # 보안 검증 로깅
                if authenticated_user_id and provided_user and provided_user != authenticated_user_id:
                    logger.warning(
                        f"⚠️ 보안: 인증된 user_id({authenticated_user_id})와 파라미터 {auth_field}({provided_user})가 다름. 인증된 user_id 사용."
                    )

                if resolved_user:
                    arguments[auth_field] = resolved_user
            # Registry를 통한 도구 실행
            response = await self.registry.call_tool(
                name=name,
                arguments=arguments,
                authenticated_user_id=authenticated_user_id
            )

            # 응답 포맷팅
            if hasattr(response, 'message'):
                return [TextContent(type="text", text=response.message)]
            elif hasattr(response, 'model_dump_json'):
                return [TextContent(type="text", text=response.model_dump_json(indent=2))]
            else:
                return [TextContent(type="text", text=str(response))]

        except ValueError as e:
            error_msg = str(e)
            logger.error(error_msg)
            return [
                TextContent(
                    type="text",
                    text=json.dumps(
                        {"success": False, "message": error_msg}, indent=2
                    ),
                )
            ]

        except Exception as e:
            logger.error(f"❌ Tool 실행 오류: {name}, {str(e)}", exc_info=True)
            error_response = {"success": False, "message": f"오류 발생: {str(e)}"}
            return [
                TextContent(type="text", text=json.dumps(error_response, indent=2))
            ]

    # ========================================================================
    # Helper: Convert to dict (for HTTP responses)
    # ========================================================================

    async def call_tool_as_dict(
        self,
        name: str,
        arguments: Dict[str, Any],
        authenticated_user_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        HTTP API용 헬퍼: call_tool 결과를 dict로 반환

        MCP는 TextContent를 반환하지만,
        HTTP API는 JSON dict를 반환해야 하므로 변환 헬퍼 제공
        """
        try:
            response = await self.registry.call_tool(
                name=name,
                arguments=arguments,
                authenticated_user_id=authenticated_user_id
            )

            if hasattr(response, 'model_dump'):
                return response.model_dump()
            elif hasattr(response, '__dict__'):
                return response.__dict__
            else:
                return {"result": str(response)}

        except Exception as e:
            logger.error(f"❌ Tool 실행 오류: {name}, {str(e)}", exc_info=True)
            raise