"""
OneNote Content Management Service
MCP Protocol Handlers - Auto-generated from tool_config.yaml
Generated at: 2025-11-11T17:27:37.524563
Source config: modules/onenote_mcp/tool_config.yaml

DO NOT EDIT THIS FILE DIRECTLY
Modify tool_config.yaml and regenerate using:
python scripts/generate_handlers.py --config modules/onenote_mcp/tool_config.yaml
"""

import json
from typing import Any, Dict, List, Optional
from mcp.types import Tool, TextContent, Prompt, PromptArgument, PromptMessage

from infra.core.logger import get_logger
from infra.core.tool_registry import ToolRegistry, ToolConfig
from .onenote_handler import OneNoteHandler
from .schemas import (    UpdatePageRequest,    UpdatePageResponse,)
logger = get_logger(__name__)


class OneNoteHandlers:
    """OneNote Content Management Service MCP Protocol Handlers"""

    def __init__(self):
        """Initialize handlers with tools instance and registry"""
        self.onenote_handler = OneNoteHandler()
        self.registry = ToolRegistry()
        self._register_tools()
        logger.info("✅ OneNoteHandlers initialized with 5 tools")

    def _register_tools(self):
        """Register all tools in the registry"""
        # manage_sections_and_pages: OneNote 섹션과 페이지를 관리합니다. action 파라미터로 동작을 지정: create_section(...
        self.registry.register(
            ToolConfig(
                name="manage_sections_and_pages",
                description="OneNote 섹션과 페이지를 관리합니다. action 파라미터로 동작을 지정: create_section(섹션 생성), list_sections(섹션 목록 조회), list_pages(페이지 목록 조회)",                request_class=dict,                response_class=dict,                method=self.onenote_handler.manage_sections_and_pages,                auth_required=True,                auth_field="user_id",                input_schema={"properties": {"action": {"description": "\uc218\ud589\ud560 \uc791\uc5c5: create_section(\uc139\uc158 \uc0dd\uc131), list_sections(\uc139\uc158 \ubaa9\ub85d), list_pages(\ud398\uc774\uc9c0 \ubaa9\ub85d)", "enum": ["create_section", "list_sections", "list_pages"], "type": "string"}, "notebook_id": {"description": "\ub178\ud2b8\ubd81 ID (create_section \uc2dc \ud544\uc218)", "type": "string"}, "page_title": {"description": "\ud398\uc774\uc9c0 \uc81c\ubaa9 (list_pages: \ud544\ud130\ub9c1\uc6a9)", "type": "string"}, "section_id": {"description": "\uc139\uc158 ID (list_pages: \ud2b9\uc815 \uc139\uc158\uc758 \ud398\uc774\uc9c0\ub9cc \uc870\ud68c)", "type": "string"}, "section_name": {"description": "\uc139\uc158 \uc774\ub984 (create_section: \uc0dd\uc131\ud560 \uc774\ub984, list_sections: \ud544\ud130\ub9c1\uc6a9, list_pages: DB\uc5d0\uc11c section_id \uc870\ud68c\uc6a9)", "type": "string"}, "user_id": {"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "type": "string"}}, "required": ["action"], "type": "object"},            )
        )
        # manage_page_content: OneNote 페이지 내용을 관리합니다. action 파라미터로 동작을 지정: get(내용 조회), crea...
        self.registry.register(
            ToolConfig(
                name="manage_page_content",
                description="OneNote 페이지 내용을 관리합니다. action 파라미터로 동작을 지정: get(내용 조회), create(페이지 생성), delete(페이지 삭제)",                request_class=dict,                response_class=dict,                method=self.onenote_handler.manage_page_content,                auth_required=True,                auth_field="user_id",                input_schema={"properties": {"action": {"description": "\uc218\ud589\ud560 \uc791\uc5c5: get(\ub0b4\uc6a9 \uc870\ud68c), create(\ud398\uc774\uc9c0 \uc0dd\uc131), delete(\ud398\uc774\uc9c0 \uc0ad\uc81c)", "enum": ["get", "create", "delete"], "type": "string"}, "content": {"description": "\ud398\uc774\uc9c0 \ub0b4\uc6a9 (HTML) (create \uc2dc \ud544\uc218)", "type": "string"}, "page_id": {"description": "\ud398\uc774\uc9c0 ID (get, delete \uc2dc \ud544\uc218)", "type": "string"}, "section_id": {"description": "\uc139\uc158 ID (create \uc2dc \ud544\uc218)", "type": "string"}, "title": {"description": "\ud398\uc774\uc9c0 \uc81c\ubaa9 (create \uc2dc \ud544\uc218)", "type": "string"}, "user_id": {"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "type": "string"}}, "required": ["action"], "type": "object"},            )
        )
        # edit_page: OneNote 페이지 내용을 편집합니다 (내용 추가/append)....
        self.registry.register(
            ToolConfig(
                name="edit_page",
                description="OneNote 페이지 내용을 편집합니다 (내용 추가/append).",                request_class=UpdatePageRequest,                response_class=UpdatePageResponse,                method=self.onenote_handler.edit_page,                auth_required=True,                auth_field="user_id",                input_schema={"properties": {"content": {"description": "\ucd94\uac00\ud560 \ub0b4\uc6a9 (HTML)", "type": "string"}, "page_id": {"description": "OneNote \ud398\uc774\uc9c0 ID", "type": "string"}, "user_id": {"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "type": "string"}}, "required": ["page_id", "content"], "type": "object"},            )
        )
        # sync_onenote_db: OneNote API에서 최신 섹션/페이지 정보를 가져와 로컬 DB와 동기화합니다. 삭제되거나 변경된 항목을...
        self.registry.register(
            ToolConfig(
                name="sync_onenote_db",
                description="OneNote API에서 최신 섹션/페이지 정보를 가져와 로컬 DB와 동기화합니다. 삭제되거나 변경된 항목을 자동으로 감지하여 DB를 업데이트합니다.",                request_class=dict,                response_class=dict,                method=self.onenote_handler.sync_onenote_db,                auth_required=True,                auth_field="user_id",                input_schema={"properties": {"sync_pages": {"default": true, "description": "\ud398\uc774\uc9c0 \ub3d9\uae30\ud654 \uc5ec\ubd80 (\uae30\ubcf8\uac12: true)", "type": "boolean"}, "sync_sections": {"default": true, "description": "\uc139\uc158 \ub3d9\uae30\ud654 \uc5ec\ubd80 (\uae30\ubcf8\uac12: true)", "type": "boolean"}, "user_id": {"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "type": "string"}}, "required": [], "type": "object"},            )
        )
        # get_recent_onenote_items: 최근 수정된 OneNote 페이지와 섹션을 조회합니다. 로컬 DB에서 last_modified_time 기준...
        self.registry.register(
            ToolConfig(
                name="get_recent_onenote_items",
                description="최근 수정된 OneNote 페이지와 섹션을 조회합니다. 로컬 DB에서 last_modified_time 기준으로 정렬하여 반환합니다.",                request_class=dict,                response_class=dict,                method=self.onenote_handler.get_recent_onenote_items,                auth_required=True,                auth_field="user_id",                input_schema={"properties": {"limit": {"default": 10, "description": "\uc870\ud68c\ud560 \ud56d\ubaa9 \uc218 (\uc139\uc158\uacfc \ud398\uc774\uc9c0 \uac01\uac01, \uae30\ubcf8\uac12: 10)", "type": "integer"}, "user_id": {"description": "\uc0ac\uc6a9\uc790 ID (OPTIONAL - \uc138\uc158\uc5d0\uc11c \uc790\ub3d9 \ub9e4\ud551\ub428)", "type": "string"}}, "required": [], "type": "object"},            )
        )

    # ========================================================================
    # MCP Protocol: list_tools
    # ========================================================================

    async def handle_list_tools(self) -> List[Tool]:
        """List available MCP tools"""
        logger.info("🔧 [MCP Handler] list_tools() called")
        return self.registry.list_tools()

    # ========================================================================
    # MCP Protocol: call_tool
    # ========================================================================

    async def handle_call_tool(
        self,
        name: str,
        arguments: Dict[str, Any],
        authenticated_user_id: Optional[str] = None
    ) -> List[TextContent]:
        """Handle MCP tool calls"""
        logger.info(f"🔨 [MCP Handler] call_tool({name}) with args: {arguments}")

        try:            # 인증 기반 user_id 강제 적용 (검색 계열 툴에만 해당)
            auth_tools = ["manage_sections_and_pages", "manage_page_content", "edit_page", "sync_onenote_db", "get_recent_onenote_items"]
            if name in auth_tools:
                from infra.core.auth_helpers import get_authenticated_user_id

                # 도구별 인증 필드 매핑
                auth_fields = {                    "manage_sections_and_pages": "user_id",                    "manage_page_content": "user_id",                    "edit_page": "user_id",                    "sync_onenote_db": "user_id",                    "get_recent_onenote_items": "user_id",                }

                auth_field = auth_fields.get(name, "user_id")
                provided_user = arguments.get(auth_field)

                # 공통 헬퍼 적용
                resolved_user = get_authenticated_user_id(
                    {"user_id": provided_user} if provided_user else {},
                    authenticated_user_id,
                )

                # 보안 검증 로깅
                if authenticated_user_id and provided_user and provided_user != authenticated_user_id:
                    logger.warning(
                        f"⚠️ 보안: 인증된 user_id({authenticated_user_id})와 파라미터 {auth_field}({provided_user})가 다름. 인증된 user_id 사용."
                    )

                if resolved_user:
                    arguments[auth_field] = resolved_user
            # Registry를 통한 도구 실행
            response = await self.registry.call_tool(
                name=name,
                arguments=arguments,
                authenticated_user_id=authenticated_user_id
            )

            # 응답 포맷팅
            if hasattr(response, 'message'):
                return [TextContent(type="text", text=response.message)]
            elif hasattr(response, 'model_dump_json'):
                return [TextContent(type="text", text=response.model_dump_json(indent=2))]
            else:
                return [TextContent(type="text", text=str(response))]

        except ValueError as e:
            error_msg = str(e)
            logger.error(error_msg)
            return [
                TextContent(
                    type="text",
                    text=json.dumps(
                        {"success": False, "message": error_msg}, indent=2
                    ),
                )
            ]

        except Exception as e:
            logger.error(f"❌ Tool 실행 오류: {name}, {str(e)}", exc_info=True)
            error_response = {"success": False, "message": f"오류 발생: {str(e)}"}
            return [
                TextContent(type="text", text=json.dumps(error_response, indent=2))
            ]

    # ========================================================================
    # Helper: Convert to dict (for HTTP responses)
    # ========================================================================

    async def call_tool_as_dict(
        self,
        name: str,
        arguments: Dict[str, Any],
        authenticated_user_id: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        HTTP API용 헬퍼: call_tool 결과를 dict로 반환

        MCP는 TextContent를 반환하지만,
        HTTP API는 JSON dict를 반환해야 하므로 변환 헬퍼 제공
        """
        try:
            response = await self.registry.call_tool(
                name=name,
                arguments=arguments,
                authenticated_user_id=authenticated_user_id
            )

            if hasattr(response, 'model_dump'):
                return response.model_dump()
            elif hasattr(response, '__dict__'):
                return response.__dict__
            else:
                return {"result": str(response)}

        except Exception as e:
            logger.error(f"❌ Tool 실행 오류: {name}, {str(e)}", exc_info=True)
            raise